
export const rows = [
  {
    id: 1,
    name: "Ever Melisanire",
    email: "evermelisanire@gmail.com",
    age: 28,
    phone: "(232)545-6269",
    access: "Admin",
  },
  {
    id: 2,
    name: "Ferrarra Clifford",
    email: "ferrarraclifford@gmail.com",
    age: 42,
    phone: "(543)124-0123",
    access: "Admin",
  },
  {
    id: 3,
    name: "Jon Snow",
    email: "jonsnow@gmail.com",
    age: 45,
    phone: "(665)121-5237",
    access: "Admin",
  },
  {
    id: 4,
    name: "Anya Stark",
    email: "anyastark@gmail.com",
    age: 46,
    phone: "(921)425-4239",
    access: "Manager",
  },
  {
    id: 5,
    name: "Corsel Lannis",
    email: "corsellannis@gmail.com",
    age: 31,
    phone: "(421)314-7739",
    access: "Manager",
  },
  {
    id: 6,
    name: "Jaime Lannis",
    email: "jaimelannis@gmail.com",
    age: 35,
    phone: "(422)902-6259",
    access: "User",
  },
  {
    id: 7,
    name: "Danniery Stangerry",
    email: "dannierystangerry@gmail.com",
    age: 44,
    phone: "(421)445-1189",
    access: "User",
  },
  {
    id: 8,
    name: "Rossini Frances",
    email: "rossinifrances@gmail.com",
    age: 36,
    phone: "(222)444-5555",
    access: "User",
  },
  {
    id: 9,
    name: "Harvey Roxie",
    email: "harveyroxie@gmail.com",
    age: 65,
    phone: "(444)555-6239",
    access: "User",
  },
];

